# Generated by Django 3.1.8 on 2021-05-14 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=200)),
                ('tw', models.CharField(max_length=50, null=True)),
                ('fb', models.CharField(max_length=50, null=True)),
                ('google', models.CharField(max_length=50, null=True)),
                ('rif', models.CharField(max_length=50)),
                ('localphone', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil de Usuario',
            },
        ),
    ]
