# Generated by Django 3.1.8 on 2021-05-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
