# Generated by Django 3.1.8 on 2021-05-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tw',
            new_name='email',
        ),
    ]
